apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h3syyzwq8-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ada3daa848.t2kf.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:d5db8ab453c29f9396802dacefc8a223ffe56cae@sha256:a72ba56963f8f3a5343edbee224c44dac2f2af4ecb5073ed103d5932c2d6b3ff
          name: container-image
